#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import editor.template_builders as build_template_rz

env.CommandNoCache("templates.gen.h", Glob("*/*.rz"), env.Run(build_template_rz.make_templates))
